# Generated by Django 4.2.6 on 2023-11-01 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0003_user_account_creation_date_user_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.FileField(blank=True, upload_to='profile_pics'),
        ),
    ]
