# Generated by Django 4.2.6 on 2023-11-05 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0009_user_follower_count_user_following_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='total_km_run',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
