# Generated by Django 4.2.6 on 2023-11-06 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0010_user_total_km_run'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('event_datetime', models.DateTimeField()),
                ('description', models.CharField(max_length=400)),
                ('route', models.FileField(blank=True, upload_to='gpx_files')),
                ('organiser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_organised', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
