# Generated by Django 4.2.6 on 2023-11-08 11:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0015_event_distance_event_duration_event_pace_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='duration',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.TimeField(default=datetime.time(11, 24, 46, 685471)),
        ),
    ]
