# Generated by Django 4.2.6 on 2023-12-01 10:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0018_alter_event_time_event_attendence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.TimeField(default=datetime.time(10, 17, 13, 614575)),
        ),
    ]
