# Generated by Django 4.2.6 on 2023-12-12 10:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0023_alter_event_date_time_alter_event_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.TimeField(default=datetime.time(10, 58, 40, 794202)),
        ),
    ]
