# Generated by Django 4.2.6 on 2023-12-18 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0026_remove_event_date_remove_event_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_eyes',
            field=models.CharField(default='smooth_shocked.svg', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar_mouth',
            field=models.CharField(default='open_wide.svg', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='use_avatar',
            field=models.BooleanField(default=True),
        ),
    ]
