# Generated by Django 4.2.6 on 2023-12-20 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0027_user_avatar_eyes_user_avatar_mouth_user_use_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_colour',
            field=models.CharField(default='#FFFF00', max_length=7),
        ),
    ]
